CREATE TABLE users (
  username VARCHAR(25) PRIMARY KEY,
  password TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL
    CHECK (position('@' IN email) > 1),
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE slots (
  level INTEGER PRIMARY KEY,
  img TEXT
);

CREATE TABLE elements (
  element TEXT PRIMARY KEY,
  img TEXT
);

CREATE TABLE locations (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  zone_count INTEGER NOT NULL,
  camps JSON,
  icon TEXT,
  imgs TEXT[]
);

CREATE TABLE items (
  id INTEGER PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  rarity INTEGER NOT NULL
);

CREATE TABLE skills (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  level INTEGER NOT NULL,
  description TEXT,
  cap INTEGER
);

CREATE TABLE ailments (
  id INTEGER PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE armor_sets (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  rank TEXT NOT NULL,
  set_bonus TEXT
);

-- by pieces
CREATE TABLE set_skills (
  id SERIAL PRIMARY KEY,
  armor_set_id INTEGER REFERENCES armor_sets INITIALLY DEFERRED ON DELETE CASCADE,
  skill_id INTEGER REFERENCES skills INITIALLY DEFERRED ON DELETE CASCADE,
  pieces INTEGER
);

CREATE TABLE armor (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  rank TEXT NOT NULL,
  slots JSON,
  rarity INTEGER NOT NULL,
  defense_base INTEGER NOT NULL,
  defense_max INTEGER NOT NULL,
  defense_augmented INTEGER NOT NULL,
  armor_set_id INTEGER REFERENCES armor_sets INITIALLY DEFERRED,
  m_img TEXT, 
  f_img TEXT
);

CREATE TABLE armor_skills (
  id SERIAL PRIMARY KEY,
  armor_id INTEGER REFERENCES armor INITIALLY DEFERRED ON DELETE CASCADE,
  skill_id INTEGER REFERENCES skills INITIALLY DEFERRED ON DELETE CASCADE
);

CREATE TABLE armor_materials (
  id SERIAL PRIMARY KEY,
  armor_id INTEGER REFERENCES armor INITIALLY DEFERRED ON DELETE CASCADE,
  item_id INTEGER REFERENCES items INITIALLY DEFERRED ON DELETE CASCADE,
  quantity INTEGER NOT NULL
);

CREATE TABLE monsters (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  species TEXT,
  description TEXT,
  icon TEXT,
  img TEXT
);

CREATE TABLE monster_locations (
  id SERIAL PRIMARY KEY,
  monster_id INTEGER REFERENCES monsters INITIALLY DEFERRED ON DELETE CASCADE,
  location_id INTEGER REFERENCES locations INITIALLY DEFERRED ON DELETE CASCADE
);

CREATE TABLE monster_weaknesses (
  id SERIAL PRIMARY KEY,
  monster_id INTEGER REFERENCES monsters INITIALLY DEFERRED ON DELETE CASCADE,
  element TEXT REFERENCES elements ON DELETE CASCADE,
  stars INTEGER NOT NULL,
  condition TEXT
);

CREATE TABLE monster_ailments (
  id SERIAL PRIMARY KEY,
  monster_id INTEGER REFERENCES monsters INITIALLY DEFERRED ON DELETE CASCADE,
  ailment_id INTEGER REFERENCES ailments INITIALLY DEFERRED ON DELETE CASCADE
);

CREATE TABLE monster_materials (
  id INTEGER PRIMARY KEY,
  monster_id INTEGER REFERENCES monsters INITIALLY DEFERRED ON DELETE CASCADE,
  item_id INTEGER REFERENCES items INITIALLY DEFERRED ON DELETE CASCADE
);

CREATE TABLE monster_material_conditions (
  id SERIAL PRIMARY KEY,
  monster_material_id INTEGER REFERENCES monster_materials INITIALLY DEFERRED ON DELETE CASCADE,
  type TEXT NOT NULL,
  rank TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  chance INTEGER NOT NULL,
  subtype TEXT
);

CREATE TABLE charms (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  level INTEGER NOT NULL,
  rarity INTEGER NOT NULL
);

CREATE TABLE charm_skills (
  id SERIAL PRIMARY KEY,
  charm_id INTEGER REFERENCES charms INITIALLY DEFERRED ON DELETE CASCADE,
  skill_id INTEGER REFERENCES skills INITIALLY DEFERRED ON DELETE CASCADE
);

CREATE TABLE charm_materials (
  id SERIAL PRIMARY KEY,
  charm_id INTEGER REFERENCES charms INITIALLY DEFERRED ON DELETE CASCADE,
  item_id INTEGER REFERENCES items INITIALLY DEFERRED ON DELETE CASCADE,
  quantity INTEGER
);

CREATE TABLE decorations (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  rarity INTEGER NOT NULL,
  slot INTEGER REFERENCES slots INITIALLY DEFERRED
);

CREATE TABLE decoration_skills (
  id SERIAL PRIMARY KEY,
  decoration_id INTEGER REFERENCES decorations INITIALLY DEFERRED ON DELETE CASCADE,
  skill_id INTEGER REFERENCES skills INITIALLY DEFERRED ON DELETE CASCADE
);

CREATE TABLE weapon_types (
  type TEXT PRIMARY KEY,
  img TEXT
);

CREATE TABLE weapons (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT REFERENCES weapon_types INITIALLY DEFERRED ON DELETE CASCADE,
  attack INTEGER NOT NULL,
  affinity INTEGER,
  defense INTEGER,
  damage_type TEXT,
  slots JSON,
  rarity INTEGER NOT NULL,
  elderseal TEXT,
  img TEXT,
  icon TEXT
);

CREATE TABLE weapon_sharpness (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE,
    -- white sharpness per handicraft level
  white_sharpness INTEGER[]
);

CREATE TABLE weapon_coatings (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE,
  coatings TEXT[]
);

CREATE TABLE weapon_phials (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE,
  phial_type TEXT NOT NULL,
  phial_damage INTEGER
);

CREATE TABLE weapon_shelling (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE,
  shelling_type TEXT NOT NULL,
  shelling_level INTEGER NOT NULL
);

CREATE TABLE weapon_boosts (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE,
  boost_type TEXT
);

CREATE TABLE weapon_gunspecs (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE, 
  special_ammo TEXT,
  deviation TEXT
);

CREATE TABLE weapon_ammo (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE,
  ammo_type TEXT NOT NULL,
  capacities INTEGER[]
);

CREATE TABLE weapon_elements (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE,
  element TEXT REFERENCES elements INITIALLY DEFERRED ON DELETE CASCADE,
  damage INTEGER NOT NULL,
  hidden BOOLEAN
);

CREATE TABLE weapon_materials (
  id SERIAL PRIMARY KEY,
  weapon_id INTEGER REFERENCES weapons INITIALLY DEFERRED ON DELETE CASCADE,
  item_id INTEGER REFERENCES items INITIALLY DEFERRED ON DELETE CASCADE,
  craft_or_upgrade TEXT NOT NULL,
  quantity INTEGER NOT NULL
);


-- USERS --------------
CREATE TABLE user_armor (
  id SERIAL PRIMARY KEY,
  username TEXT REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
  armor_id INTEGER REFERENCES armor ON DELETE CASCADE,
  slots JSON
);

CREATE TABLE user_weapons (
  id SERIAL PRIMARY KEY,
  username TEXT REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
  weapon_id INTEGER REFERENCES weapons ON DELETE CASCADE,
  slots JSON
);

CREATE TABLE user_charms (
  id SERIAL PRIMARY KEY,
  username TEXT REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
  charm_id INTEGER REFERENCES charms ON DELETE CASCADE
);

CREATE TABLE user_decorations (
  id SERIAL PRIMARY KEY,
  username TEXT REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
  decoration_id INTEGER REFERENCES decorations ON DELETE CASCADE
);

CREATE TABLE user_monsters (
  id SERIAL PRIMARY KEY,
  username TEXT REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE, 
  monster_id INTEGER REFERENCES monsters ON DELETE CASCADE
);